// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: access_level.sql

package contentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAccessLevel = `-- name: GetAccessLevel :one
select id, workspace_id, name, can_view, can_download, can_watermark, created_at, updated_at from access_levels
where id = $1 and (workspace_id is null or workspace_id = $2)
`

type GetAccessLevelParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetAccessLevel(ctx context.Context, arg GetAccessLevelParams) (AccessLevel, error) {
	row := q.db.QueryRow(ctx, getAccessLevel, arg.ID, arg.WorkspaceID)
	var i AccessLevel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.CanView,
		&i.CanDownload,
		&i.CanWatermark,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSystemAccessLevelByName = `-- name: GetSystemAccessLevelByName :one
select id, workspace_id, name, can_view, can_download, can_watermark, created_at, updated_at from access_levels
where workspace_id is null and name = $1
`

func (q *Queries) GetSystemAccessLevelByName(ctx context.Context, name string) (AccessLevel, error) {
	row := q.db.QueryRow(ctx, getSystemAccessLevelByName, name)
	var i AccessLevel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.CanView,
		&i.CanDownload,
		&i.CanWatermark,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccessLevels = `-- name: ListAccessLevels :many
select id, workspace_id, name, can_view, can_download, can_watermark, created_at, updated_at from access_levels
where workspace_id is null or workspace_id = $1
order by workspace_id nulls first, name
`

func (q *Queries) ListAccessLevels(ctx context.Context, workspaceID pgtype.UUID) ([]AccessLevel, error) {
	rows, err := q.db.Query(ctx, listAccessLevels, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessLevel
	for rows.Next() {
		var i AccessLevel
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.CanView,
			&i.CanDownload,
			&i.CanWatermark,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
