// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: document.sql

package contentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDocument = `-- name: CreateDocument :one
insert into documents 
    (workspace_id, folder_id, name, uploaded_by)
values
    ($1, $2, $3, $4)
returning id, workspace_id, folder_id, name, current_version_id, uploaded_by, created_at, updated_at
`

type CreateDocumentParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	FolderID    pgtype.UUID `json:"folder_id"`
	Name        string      `json:"name"`
	UploadedBy  pgtype.UUID `json:"uploaded_by"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.WorkspaceID,
		arg.FolderID,
		arg.Name,
		arg.UploadedBy,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FolderID,
		&i.Name,
		&i.CurrentVersionID,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDocumentVersion = `-- name: CreateDocumentVersion :one
insert into document_versions
    (document_id, version_no, mime, size, storage_key, uploaded_by)
values 
    ($1, $2, $3, $4, $5, $6)
returning id, document_id, version_no, mime, size, storage_key, uploaded_by, created_at
`

type CreateDocumentVersionParams struct {
	DocumentID pgtype.UUID `json:"document_id"`
	VersionNo  int32       `json:"version_no"`
	Mime       string      `json:"mime"`
	Size       int64       `json:"size"`
	StorageKey string      `json:"storage_key"`
	UploadedBy pgtype.UUID `json:"uploaded_by"`
}

func (q *Queries) CreateDocumentVersion(ctx context.Context, arg CreateDocumentVersionParams) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, createDocumentVersion,
		arg.DocumentID,
		arg.VersionNo,
		arg.Mime,
		arg.Size,
		arg.StorageKey,
		arg.UploadedBy,
	)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.VersionNo,
		&i.Mime,
		&i.Size,
		&i.StorageKey,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
delete from documents where id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocument, id)
	return err
}

const getCurrentVersion = `-- name: GetCurrentVersion :one
select v.id, v.document_id, v.version_no, v.mime, v.size, v.storage_key, v.uploaded_by, v.created_at from document_versions v 
join documents d on d.current_version_id = v.id
where d.id = $1
`

func (q *Queries) GetCurrentVersion(ctx context.Context, id pgtype.UUID) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, getCurrentVersion, id)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.VersionNo,
		&i.Mime,
		&i.Size,
		&i.StorageKey,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getDocumentByID = `-- name: GetDocumentByID :one
select id, workspace_id, folder_id, name, current_version_id, uploaded_by, created_at, updated_at from documents where id = $1
`

func (q *Queries) GetDocumentByID(ctx context.Context, id pgtype.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FolderID,
		&i.Name,
		&i.CurrentVersionID,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNextVersionNo = `-- name: GetNextVersionNo :one
select coalesce(max(version_no),0)::int + 1 as next_no
from document_versions where document_id = $1
`

func (q *Queries) GetNextVersionNo(ctx context.Context, documentID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getNextVersionNo, documentID)
	var next_no int32
	err := row.Scan(&next_no)
	return next_no, err
}

const getVersionByID = `-- name: GetVersionByID :one
select id, document_id, version_no, mime, size, storage_key, uploaded_by, created_at from document_versions where id = $1
`

func (q *Queries) GetVersionByID(ctx context.Context, id pgtype.UUID) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, getVersionByID, id)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.VersionNo,
		&i.Mime,
		&i.Size,
		&i.StorageKey,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listDocumentsByFolder = `-- name: ListDocumentsByFolder :many
select
    d.id,
    d.name,
    d.folder_id,
    d.current_version_id,
    d.uploaded_by,
    d.created_at,
    d.updated_at,
    v.version_no,
    v.mime,
    v.size
from documents d
join document_versions v on v.id = d.current_version_id
where d.folder_id = $1
order by d.name, d.created_at
`

type ListDocumentsByFolderRow struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	FolderID         pgtype.UUID        `json:"folder_id"`
	CurrentVersionID pgtype.UUID        `json:"current_version_id"`
	UploadedBy       pgtype.UUID        `json:"uploaded_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	VersionNo        int32              `json:"version_no"`
	Mime             string             `json:"mime"`
	Size             int64              `json:"size"`
}

func (q *Queries) ListDocumentsByFolder(ctx context.Context, folderID pgtype.UUID) ([]ListDocumentsByFolderRow, error) {
	rows, err := q.db.Query(ctx, listDocumentsByFolder, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsByFolderRow
	for rows.Next() {
		var i ListDocumentsByFolderRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FolderID,
			&i.CurrentVersionID,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VersionNo,
			&i.Mime,
			&i.Size,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersionByDocument = `-- name: ListVersionByDocument :many
select id, document_id, version_no, mime, size, storage_key, uploaded_by, created_at from document_versions where document_id = $1 order by version_no desc
`

func (q *Queries) ListVersionByDocument(ctx context.Context, documentID pgtype.UUID) ([]DocumentVersion, error) {
	rows, err := q.db.Query(ctx, listVersionByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentVersion
	for rows.Next() {
		var i DocumentVersion
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.VersionNo,
			&i.Mime,
			&i.Size,
			&i.StorageKey,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveDocument = `-- name: MoveDocument :exec
update documents set folder_id = $2, updated_at = now() where id = $1
`

type MoveDocumentParams struct {
	ID       pgtype.UUID `json:"id"`
	FolderID pgtype.UUID `json:"folder_id"`
}

func (q *Queries) MoveDocument(ctx context.Context, arg MoveDocumentParams) error {
	_, err := q.db.Exec(ctx, moveDocument, arg.ID, arg.FolderID)
	return err
}

const setCurrentVersion = `-- name: SetCurrentVersion :exec
update documents set 
    current_version_id = $2,
    updated_at = now()
where id = $1
`

type SetCurrentVersionParams struct {
	ID               pgtype.UUID `json:"id"`
	CurrentVersionID pgtype.UUID `json:"current_version_id"`
}

func (q *Queries) SetCurrentVersion(ctx context.Context, arg SetCurrentVersionParams) error {
	_, err := q.db.Exec(ctx, setCurrentVersion, arg.ID, arg.CurrentVersionID)
	return err
}
