// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: folder_access.sql

package contentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listFolderAccess = `-- name: ListFolderAccess :many
select
    fa.folder_id,
    fa.group_id,
    g.name as group_name,
    fa.level_id,
    l.name as level_name,
    l.can_view,
    l.can_download,
    l.can_watermark
from folder_access fa
join folders f on f.id = fa.folder_id
join workspace_groups g on g.id = fa.group_id
join access_levels l on l.id = fa.level_id
where fa.folder_id = $1 and f.workspace_id = $2
order by g.name
`

type ListFolderAccessParams struct {
	FolderID    pgtype.UUID `json:"folder_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

type ListFolderAccessRow struct {
	FolderID     pgtype.UUID `json:"folder_id"`
	GroupID      pgtype.UUID `json:"group_id"`
	GroupName    string      `json:"group_name"`
	LevelID      pgtype.UUID `json:"level_id"`
	LevelName    string      `json:"level_name"`
	CanView      bool        `json:"can_view"`
	CanDownload  bool        `json:"can_download"`
	CanWatermark bool        `json:"can_watermark"`
}

func (q *Queries) ListFolderAccess(ctx context.Context, arg ListFolderAccessParams) ([]ListFolderAccessRow, error) {
	rows, err := q.db.Query(ctx, listFolderAccess, arg.FolderID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFolderAccessRow
	for rows.Next() {
		var i ListFolderAccessRow
		if err := rows.Scan(
			&i.FolderID,
			&i.GroupID,
			&i.GroupName,
			&i.LevelID,
			&i.LevelName,
			&i.CanView,
			&i.CanDownload,
			&i.CanWatermark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFolderAccess = `-- name: RemoveFolderAccess :exec
delete from folder_access fa 
using folders f 
where fa.folder_id = f.id
and fa.folder_id = $1
and fa.group_id = $2
and f.workspace_id = $3
`

type RemoveFolderAccessParams struct {
	FolderID    pgtype.UUID `json:"folder_id"`
	GroupID     pgtype.UUID `json:"group_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) RemoveFolderAccess(ctx context.Context, arg RemoveFolderAccessParams) error {
	_, err := q.db.Exec(ctx, removeFolderAccess, arg.FolderID, arg.GroupID, arg.WorkspaceID)
	return err
}

const setFolderAccess = `-- name: SetFolderAccess :one
insert into folder_access (folder_id, group_id, level_id)
select f.id, g.id, l.id
from folders f
join workspace_groups g
    on g.id = $1 and g.workspace_id = f.workspace_id
join access_levels l
    on l.id = $2 and (l.workspace_id is null or l.workspace_id = f.workspace_id)
where f.id = $3 and f.workspace_id = $4
on conflict (folder_id, group_id) do update
    set
        level_id = excluded.level_id,
        updated_at = now()
returning folder_id, group_id, level_id, created_at, updated_at
`

type SetFolderAccessParams struct {
	GroupID     pgtype.UUID `json:"group_id"`
	LevelID     pgtype.UUID `json:"level_id"`
	FolderID    pgtype.UUID `json:"folder_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) SetFolderAccess(ctx context.Context, arg SetFolderAccessParams) (FolderAccess, error) {
	row := q.db.QueryRow(ctx, setFolderAccess,
		arg.GroupID,
		arg.LevelID,
		arg.FolderID,
		arg.WorkspaceID,
	)
	var i FolderAccess
	err := row.Scan(
		&i.FolderID,
		&i.GroupID,
		&i.LevelID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
