// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: folder.sql

package contentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDefaultFolder = `-- name: CreateDefaultFolder :one
insert into folders
    (workspace_id, parent_id, name, position, created_by, is_default)
values
    ($1, null, $2, 0, $3, true)
returning id, workspace_id, parent_id, name, position, created_by, created_at, updated_at, is_default
`

type CreateDefaultFolderParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Name        string      `json:"name"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateDefaultFolder(ctx context.Context, arg CreateDefaultFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, createDefaultFolder, arg.WorkspaceID, arg.Name, arg.CreatedBy)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.Name,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
	)
	return i, err
}

const createFolder = `-- name: CreateFolder :one
insert into folders
    (workspace_id, parent_id, name, position, created_by)
values
    ($1, $2, $3, $4, $5)
returning id, workspace_id, parent_id, name, position, created_by, created_at, updated_at, is_default
`

type CreateFolderParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ParentID    pgtype.UUID `json:"parent_id"`
	Name        string      `json:"name"`
	Position    int32       `json:"position"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, createFolder,
		arg.WorkspaceID,
		arg.ParentID,
		arg.Name,
		arg.Position,
		arg.CreatedBy,
	)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.Name,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
	)
	return i, err
}

const deleteFolder = `-- name: DeleteFolder :exec
delete from folders where id = $1
`

func (q *Queries) DeleteFolder(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFolder, id)
	return err
}

const getFolderByID = `-- name: GetFolderByID :one
select id, workspace_id, parent_id, name, position, created_by, created_at, updated_at, is_default from folders where id = $1
`

func (q *Queries) GetFolderByID(ctx context.Context, id pgtype.UUID) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolderByID, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.Name,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
	)
	return i, err
}

const getFolderByNameInParent = `-- name: GetFolderByNameInParent :one
select id, workspace_id, parent_id, name, position, created_by, created_at, updated_at, is_default from folders
where workspace_id = $1
    and parent_id is not distinct from $2
    and name = $3
`

type GetFolderByNameInParentParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ParentID    pgtype.UUID `json:"parent_id"`
	Name        string      `json:"name"`
}

func (q *Queries) GetFolderByNameInParent(ctx context.Context, arg GetFolderByNameInParentParams) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolderByNameInParent, arg.WorkspaceID, arg.ParentID, arg.Name)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.Name,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
	)
	return i, err
}

const getFoldersByWorkspace = `-- name: GetFoldersByWorkspace :many
select id, workspace_id, parent_id, name, position, created_by, created_at, updated_at, is_default from folders where workspace_id = $1
order by parent_id nulls first, position, created_at
`

func (q *Queries) GetFoldersByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]Folder, error) {
	rows, err := q.db.Query(ctx, getFoldersByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ParentID,
			&i.Name,
			&i.Position,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaxPositionInParent = `-- name: GetMaxPositionInParent :one
select coalesce(max(position), -1)::int as max_position
from folders
where workspace_id = $1 and parent_id is not distinct from $2
`

type GetMaxPositionInParentParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ParentID    pgtype.UUID `json:"parent_id"`
}

func (q *Queries) GetMaxPositionInParent(ctx context.Context, arg GetMaxPositionInParentParams) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxPositionInParent, arg.WorkspaceID, arg.ParentID)
	var max_position int32
	err := row.Scan(&max_position)
	return max_position, err
}

const lockWorkspaceStructure = `-- name: LockWorkspaceStructure :exec
select pg_advisory_xact_lock(hashtext($1::uuid::text))
`

func (q *Queries) LockWorkspaceStructure(ctx context.Context, workspaceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, lockWorkspaceStructure, workspaceID)
	return err
}

const moveFolder = `-- name: MoveFolder :exec
update folders set
    parent_id = $2,
    position = $3,
    updated_at = now()
where id = $1
`

type MoveFolderParams struct {
	ID       pgtype.UUID `json:"id"`
	ParentID pgtype.UUID `json:"parent_id"`
	Position int32       `json:"position"`
}

func (q *Queries) MoveFolder(ctx context.Context, arg MoveFolderParams) error {
	_, err := q.db.Exec(ctx, moveFolder, arg.ID, arg.ParentID, arg.Position)
	return err
}

const reindexFolderSiblings = `-- name: ReindexFolderSiblings :exec
with ordered as (
    select f.id as folder_id,
        (row_number() over (
            order by position,
                    case when f.id = $1 then 0 else 1 end,
                    f.name
        ))::int - 1 as rn
    from folders f
    where f.workspace_id = $2
    and f.parent_id is not distinct from $3
)
update folders t 
set position = o.rn 
from ordered o 
where t.id = o.id and t.position <> o.rn
`

type ReindexFolderSiblingsParams struct {
	MovedID     pgtype.UUID `json:"moved_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ParentID    pgtype.UUID `json:"parent_id"`
}

func (q *Queries) ReindexFolderSiblings(ctx context.Context, arg ReindexFolderSiblingsParams) error {
	_, err := q.db.Exec(ctx, reindexFolderSiblings, arg.MovedID, arg.WorkspaceID, arg.ParentID)
	return err
}

const renameFolder = `-- name: RenameFolder :one
update folders set name = $2, updated_at = now() where id = $1 returning id, workspace_id, parent_id, name, position, created_by, created_at, updated_at, is_default
`

type RenameFolderParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) RenameFolder(ctx context.Context, arg RenameFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, renameFolder, arg.ID, arg.Name)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.Name,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
	)
	return i, err
}
