// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package contentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error)
	DeleteFolder(ctx context.Context, id pgtype.UUID) error
	GetFolderByID(ctx context.Context, id pgtype.UUID) (Folder, error)
	GetFoldersByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]Folder, error)
	GetMaxPositionInParent(ctx context.Context, arg GetMaxPositionInParentParams) (int32, error)
	MoveFolder(ctx context.Context, arg MoveFolderParams) error
	RenameFolder(ctx context.Context, arg RenameFolderParams) (Folder, error)
}

var _ Querier = (*Queries)(nil)
